version: '2.0'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    restart: always
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379